# -*- coding: utf-8 -*-
"""arima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XMuN-1bsSIiRcNQ_qUSxdl1NoalJCg09
"""

import streamlit as st
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA

# Read CSV file
df = pd.read_csv("D:/Forecasting_project/Gold_data.csv",parse_dates=['date'], index_col='date')

# Set up Streamlit app
st.title('GOLD price Prediction')

# Get user input for number of days to predict
n_days = st.number_input('Number of days to predict:', value=7)

# Fit ARIMA model
model = ARIMA(df, order=(5,1,5))
model_fit = model.fit()

# Predict next n days
forecast = model_fit.forecast(steps=n_days)

# Generate dates for the forecasted period
last_date = df.index[-1]
forecast_dates = pd.date_range(start=last_date + pd.DateOffset(days=1), periods=n_days)

# Display the predicted values
st.subheader('Predicted Values:')
predicted_df = pd.DataFrame({ 'Prediction': forecast})
st.dataframe(predicted_df)